// Build-time generator for the hero's figlet name banner.
//
// figlet is a devDependency: this script bakes its output into `lib/banner.ts`, which is
// what ships. Nothing about figlet — the package, its .flf fonts, the render cost — ever
// reaches the client bundle. Run `npm run banner` after changing the words or the font;
// `tests/banner.test.ts` re-renders and fails if the committed module has gone stale.
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import figlet from "figlet";

/** The two lines of the banner, stacked. */
export const WORDS = ["LUCAS", "ROCCHETTI"];

/** The blocky Dracula-friendly face; "Big" is the plain fallback if it ever goes missing. */
export const FONT = "ANSI Shadow";
export const FALLBACK_FONT = "Big";

/**
 * The widest the banner may get. At the ~0.6em advance of a monospace cell, 72 columns is
 * what still fits a 390px phone at a legible size; past that the type gets too small.
 */
export const MAX_COLS = 72;

/**
 * figlet pads every line out to the width of the widest one and leaves a blank line under
 * the glyphs. Strip both, so the caller sees only the rows that carry ink.
 */
function renderRows(word, font) {
  const rows = figlet
    .textSync(word, { font })
    .split("\n")
    .map((row) => row.replace(/\s+$/, ""));
  while (rows.length > 0 && rows[rows.length - 1] === "") rows.pop();
  return rows;
}

/**
 * Renders the words and right-pads every row of every word to one common width, so the
 * banner is a single rectangular block and `cols` describes all of it.
 *
 * @returns {{ words: string[]; cols: number }}
 */
export function buildBanner() {
  let rendered;
  try {
    rendered = WORDS.map((word) => renderRows(word, FONT));
  } catch {
    rendered = WORDS.map((word) => renderRows(word, FALLBACK_FONT));
  }

  const cols = Math.max(...rendered.flat().map((row) => row.length));
  if (cols > MAX_COLS) {
    throw new Error(`banner is ${cols} columns wide, over the ${MAX_COLS}-column cap`);
  }

  return {
    words: rendered.map((rows) => rows.map((row) => row.padEnd(cols, " ")).join("\n")),
    cols,
  };
}

/** The exact source text of `lib/banner.ts`, so the test can diff the committed file. */
export function emit({ words, cols }) {
  return `// Generated by scripts/banner/generate.mjs — do not edit. Run \`npm run banner\`.
// figlet renders this at build time so the font never ships to the browser.
export const banner = {
  words: [
${words.map((word) => `    ${JSON.stringify(word)},`).join("\n")}
  ],
  cols: ${cols},
} as const;
`;
}

/** Where the generated module lands. */
export const OUT_FILE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "lib",
  "banner.ts",
);

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const built = buildBanner();
  writeFileSync(OUT_FILE, emit(built), "utf8");
  console.log(`wrote ${path.relative(process.cwd(), OUT_FILE)} — ${built.cols} columns`);
}
