// Generated by scripts/banner/generate.mjs — do not edit. Run `npm run banner`.
// figlet renders this at build time so the font never ships to the browser.
export const banner = {
  words: [
    "  _    _   _  ____    _    ____                      \n | |  | | | |/ ___|  / \\  / ___|                     \n | |  | | | | |     / _ \\ \\___ \\                     \n | |__| |_| | |___ / ___ \\ ___) |                    \n |_____\\___/ \\____/_/   \\_\\____/                     ",
    "  ____   ___   ____ ____ _   _ _____ _____ _____ ___ \n |  _ \\ / _ \\ / ___/ ___| | | | ____|_   _|_   _|_ _|\n | |_) | | | | |  | |   | |_| |  _|   | |   | |  | | \n |  _ <| |_| | |__| |___|  _  | |___  | |   | |  | | \n |_| \\_\\\\___/ \\____\\____|_| |_|_____| |_|   |_| |___|",
  ],
  cols: 53,
} as const;
